global:
  resolve_timeout: 5m

route:
  receiver: webhook
  group_wait: 0s
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: webhook
    webhook_configs:
      - url: 'http://webhook:5001/'
        send_resolved: true
