version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - nginx-exporter

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  nginx-service:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: [
      '--nginx.scrape-uri=http://nginx-service/nginx_status'
    ]
    depends_on:
      - nginx-service

  webhook:
    build: ./webhook
    ports:
      - 5001:5000
    volumes:
      - ./webhook:/webhook
    depends_on:
      - alertmanager
      - nginx-service

networks:
  default:
    driver: bridge
