groups:
  - name: nginx-alerts
    rules:
      - alert: NginxDown
        expr: nginx_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Nginx microservice is down"
          description: "Nginx container has been down for more than 30 seconds."
